apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: Sample
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: Sample
    tanzu.app.live.view: true
    tanzu.app.live.view.application.flavours: steeltoe
    tanzu.app.live.view.application.name: Sample
spec:
  source:
    git:
      url: https://github.com/mgbrodi/Sample
      ref:
        branch: main
